name: Aman
description: "Bus Management System"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.20.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Design
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.0
  flutter_svg_provider: ^1.0.7
  lottie: ^3.3.1
  shimmer: ^3.0.0
  introduction_screen: ^3.1.17
  cached_network_image: ^3.4.1
  croppy: ^1.3.6
  device_preview: ^1.3.1
  vector_graphics: any

  # State Management & DI
  flutter_bloc: ^9.1.1
  hydrated_bloc: ^10.1.1
  bloc: any
  get_it: ^8.0.3
  equatable: ^2.0.7

  # Local Storage
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5
  flutter_secure_storage: ^9.2.4
  sqflite: any
  path: any

  # Networking & APIs
  dio: ^5.8.0+1
  connectivity_plus: ^6.1.4
  dartz: ^0.10.1
  logger: any
  crypto: any

  # Firebase & Cloud Services
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  firebase_storage: ^13.0.0
  cloud_firestore: ^6.0.0
  firebase_messaging: ^16.0.0
  firebase_analytics: ^12.0.0
  firebase_crashlytics: ^5.0.0
  firebase_remote_config: ^6.0.0

  # Authentication Providers
  google_sign_in: ^7.1.1
  sign_in_with_apple: ^7.0.1

  # OTP and Phone Number
  pinput: ^5.0.0
  intl_phone_number_input: ^0.7.4
  country_code_picker: ^3.0.0

  # Utilities
  intl: ^0.20.2
  timezone: ^0.10.1
  device_info_plus: ^11.5.0
  url_launcher: ^6.3.1
  share_plus: ^10.1.2
  package_info_plus: ^8.3.0
  flash: ^3.1.1
  easy_localization: ^3.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_gen_runner: ^5.11.0
  build_runner: ^2.4.15
  package_rename: ^1.10.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.4

# Flutter Gen Config
flutter_gen:
  output: lib/generated/
  integrations:
    flutter_svg: true
    lottie: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/
    - assets/animations/

# Launcher Icons Config
flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/app_logo.png"
  image_path: "assets/images/app_logo.png"
  web:
    generate: true
    image_path: "assets/images/app_logo.png"
    background_color: "#000000"

# Native Splash Config
flutter_native_splash:
  color: "#ffffff"
  color_dark: "#000000"
  image: assets/images/app_logo.png
  image_dark: assets/images/app_logo.png
  fullscreen: true
  android_gravity: center

  android_12:
    image: assets/images/app_logo.png
    image_dark: assets/images/app_logo.png
    color: "#ffffff"
    color_dark: "#000000"
    android_gravity: center
  android: true
  ios: true
  web: true

# Package Rename Config
package_rename_config:
  android:
    app_name: "Aman"
    package_name: "com.Aman.app"

  ios:
    app_name: "Aman"
    bundle_name: "Aman"
    package_name: "com.Aman.app"
