// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8IZE4VHvjhKhXBsL2F6HEPFxlsYZ_y2Y',
    appId: '1:1018051462148:web:89ee4162188a5126c7e151',
    messagingSenderId: '1018051462148',
    projectId: 'aman-49e04',
    authDomain: 'aman-49e04.firebaseapp.com',
    storageBucket: 'aman-49e04.firebasestorage.app',
    measurementId: 'G-FFPRZH2PXS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsElDdjI_SpcR2T9uxZKaiujHESb8Ei3M',
    appId: '1:1018051462148:android:5306926baf79ffaec7e151',
    messagingSenderId: '1018051462148',
    projectId: 'aman-49e04',
    storageBucket: 'aman-49e04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjM_EeyADXswTA_bhob-5gilLO3zapeNs',
    appId: '1:1018051462148:ios:ff020df63c99053ac7e151',
    messagingSenderId: '1018051462148',
    projectId: 'aman-49e04',
    storageBucket: 'aman-49e04.firebasestorage.app',
    iosBundleId: 'com.Aman.app',
  );
}
